name: 'Terraform'

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: 'Terraform'
    env:
      # AWS secrets
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Initialize a new or existing Terraform working directory
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.9.8
          tf_actions_subcommand: "init"
          tf_actions_working_dir: "."
          tf_actions_comment: true
          args: '-var="instance_type=t2.medium"'

      # Run Terraform plan
      - name: Terraform plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.9.8
          tf_actions_subcommand: "plan"
          tf_actions_working_dir: "."
          tf_actions_comment: true
          args: '-var="instance_type=t2.medium"'

      # Run Terraform apply
      - name: Terraform apply
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.9.8
          tf_actions_subcommand: "apply"
          tf_actions_working_dir: "."
          tf_actions_comment: true
          args: '-auto-approve -var="instance_type=t2.medium"'
        

